env: dev

sql:
  instance: carbon-1287:europe-west1:uttu-db-1=tcp:5432

configMap:
  organisationRegistryUrl: https://api.dev.entur.io/organisations/v1/register/organisations/
  keycloakUrl: https://kc-dev.devstage.entur.io/auth
  pubsubProjectId: carbon-1287
  blobstoreProjectId: carbon-1287
  blobstoreContainerName: marduk-exchange
  logLevel: DEBUG
  flywayTable: schema_version