env: production

replicas: 2

resources:
  cpuLimit: 500m
  memLimit: 2000Mi
  cpuRequest: 200m
  memRequest: 1500Mi
  xss: 1024m
  xmx: 1000m

sql:
  instance: neon-1287:europe-west1:uttu-db-1=tcp:5432

configMap:
  organisationRegistryUrl: https://api.entur.io/organisations/v1/register/organisations/
  projectId: neon-1287
  keycloakUrl: https://auth.entur.org/auth/
  blobstoreContainerName: marduk-exchange-production
  logLevel: INFO
  flywayTable: flyway_schema_history