env: prod

replicas: 2

resources:
  cpuLimit: 500m
  memLimit: 2000Mi
  cpuRequest: 200m
  memRequest: 1500Mi
  xss: 1024m
  xmx: 1000m

sql:
  instance: entur-ror-prod:europe-west1:uttu-db-pg13=tcp:5432

configMap:
  organisationRegistryUrl: https://api.entur.io/organisations/v1/register/organisations/
  auth0:
    ror:
      url: https://auth2.entur.org/
      audience: https://ror.api.entur.io
    partner:
      tokenUri: https://partner.entur.org/oauth/token
      clientId: 1ZZMds7c0urOXHAMuklhv2puDcdVUQIW
  orgRegister:
    audience: https://api.entur.io
  pubsubProjectId: entur-ror-prod
  blobstoreProjectId: entur-ror-prod
  blobstoreContainerName: ror-marduk-exchange-production
  logLevel: INFO
  flywayTable: flyway_schema_history

