env: dev

sql:
  instance: entur-ror-dev:europe-west1:uttu-db-pg13=tcp:5432

configMap:
  organisationRegistryUrl: https://api.dev.entur.io/organisations/v1/register/organisations/
  auth0:
    ror:
      url: https://ror-entur-dev.eu.auth0.com/
      audience: https://ror.api.dev.entur.io
    partner:
      tokenUri: https://partner.dev.entur.org/oauth/token
      clientId: 4a5zhKZaENqIl1u0m5blot8sYKVTUIec
  orgRegister:
    audience: https://api.dev.entur.io
  pubsubProjectId: entur-ror-dev
  blobstoreProjectId: entur-ror-dev
  blobstoreContainerName: ror-marduk-exchange-dev
  logLevel: DEBUG
  flywayTable: schema_version
