version: 2
aliases:
- &GCP-auth
  name: Authenticate with GCP SA credentials
  command: |
    echo $GCLOUD_SERVICE_KEY > ${HOME}/account-auth.json
    ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
- &install-docker-client
  name: Install Docker client
  command: |
    set -x
    VER="18.03.1-ce"
    curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
    tar -xz -C /tmp -f /tmp/docker-$VER.tgz
    mv /tmp/docker/* /usr/bin
- &install-gcloud
  name: Install gcloud
  command: |
    set -x
    VER="218.0.0-linux-x86_64"
    wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${VER}.tar.gz
    tar -xvzf google-cloud-sdk-${VER}.tar.gz
    ./google-cloud-sdk/install.sh -q
    ./google-cloud-sdk/bin/gcloud components update
- &docker-login
  name: Docker login
  command: |
    cat ${HOME}/account-auth.json | docker login -u _json_key --password-stdin https://eu.gcr.io
- &post-hook
  name: Notify about build and docker image pushed
  command: |
    echo "{\"name\": \"${CIRCLE_PROJECT_REPONAME}\", \"build\": {\"status\": \"SUCCESS\", \"phase\": \"FINALIZED\", \"scm\": {\"commit\": \"${CIRCLE_SHA1}\"}}}" > message.json
    echo sending: $(cat message.json)
    curl -X POST --data @message.json -H "apiKey: ${BUILD_STATUS_API_KEY}" -H "Content-Type: application/json" -H "ET-Client-Name: CircleCI" -H "ET-Client-ID: CircleCI-${CIRCLE_PROJECT_REPONAME}"  "${BUILD_STATUS_URL}"
jobs:
  build:
    docker:
    - image: maven:3.5.4-jdk-8
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn install -s .circleci/settings.xml
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
    - persist_to_workspace:
        root: ~/project
        paths:
        - target
        - pom.xml
        - .circleci
  deploy-docker:
    docker:
    - image: maven:3.5.4-jdk-8
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
    - attach_workspace:
        at: ~/project
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - setup_remote_docker:
        docker_layer_caching: true
    - run: *install-gcloud
    - run: *GCP-auth
    - run: *install-docker-client
    - run: *docker-login
    - run:
        name: Docker build and push
        command: mvn docker:build docker:push -s .circleci/settings.xml
    - run: *post-hook
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build:
        context: org-carbon
    - deploy-docker:
        context: org-carbon
        requires:
        - build
        filters:
          branches:
            only: master