apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  application.properties: |-
    organisation.registry.url={{ .Values.configMap.organisationRegistryUrl }}
    export.notify.enabled=true
    export.notify.queue.name=ChouetteMergeWithFlexibleLinesQueue

    # gcs
    blobstore.gcs.project.id={{ .Values.configMap.projectId }}
    blobstore.gcs.credential.path=/etc/uttu/uttu-service-account.json
    blobstore.gcs.container.name=marduk-exchange

    # pubsub
    spring.cloud.gcp.pubsub.project-id={{ .Values.configMap.projectId }}
    spring.cloud.gcp.pubsub.credentials.location=file:/etc/marduk-pubsub-account/marduk-pubsub-credentials.json
    spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
    spring.cloud.gcp.pubsub.subscriber.executor-threads=30
    spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period=36000

    # Database properties
    spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
    spring.jpa.open-in-view=false
    spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
    spring.jpa.database=POSTGRESQL
    spring.jpa.hibernate.ddl-auto=none
    spring.database.driverClassName=org.postgresql.Driver
    spring.datasource.url=jdbc:postgresql://localhost:5432/uttu
    spring.datasource.platform=postgres
    spring.datasource.username=uttu
    spring.flyway.table=schema_version

    # Keycloak
    authorization.enabled=true
    keycloak.realm=rutebanken
    keycloak.principal-attribute=preferred_username
    keycloak.resource=uttu
    keycloak.auth-server-url={{ .Values.configMap.keycloakUrl }}
    # Temporary setting until bug in KeycloakWebSecurityConfigurerAdapter is fixed (The bean ''httpSessionManager'', defined in class path resource XXXSecurityConfiguration.class],could not be registered. A bean with that name has already been defined in URL)
    spring.main.allow-bean-definition-overriding=true

    # Logging
    logging.level.no.entur.uttu=DEBUG
    logging.level.no.entur.uttu.health.rest.HealthResource=INFO

    # Profile
    spring.profiles.active=gcs-blobstore