{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-admin-v1-flexible-lines
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- if eq .Values.env "production"}}
  - host: timetable-admin-v1-flexible-lines-{{ .Release.Namespace }}.entur.io
  {{ else }}
  - host: timetable-admin-v1-flexible-lines-{{ .Release.Namespace }}.{{ .Release.Namespace }}.entur.io
  {{- end}}
    http:
      paths:
        - backend:
            serviceName: {{ template "app.name" . }}
            servicePort: {{ .Values.service.http.externalPort }}
  {{- end }}