apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "uttu.common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-admin-v1-flexible-lines
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: timetable-admin-v1-flexible-lines{{ .Values.ingress.domainName }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "app.name" . }}
              port:
                number: {{ .Values.common.service.externalPort }}