common:
  app: uttu
  shortname: uttu
  team: ror
  ingress:
    enabled: false
  service:
    externalPort: 80
    internalPort: 8080
  container:
    forceReplicas: 1
    image: <+artifacts.primary.image>
    cpu: 1
    memory: 2000
    memoryLimit: 3000
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: uttu-application
        name: application-config
  postgres:
    enabled: true
    memory: 40
  configmap:
    data:
      JDK_JAVA_OPTIONS:  -server -Xmx2048m -Xss1024m -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true