name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Oslo
    steps:
      - uses: actions/checkout@v5

      # nodejs is needed because the dynamic download of it via the prettier maven plugin often
      # times out
      # Example: https://github.com/opentripplanner/OpenTripPlanner/actions/runs/4490450225/jobs/7897533439
      - uses: actions/setup-node@v5
        with:
          node-version: 18.20.8

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Run tests
        run: |
          sudo timedatectl set-timezone "Europe/Oslo"
          ./mvnw --batch-mode jacoco:prepare-agent test jacoco:report -Dprettier.nodePath=node -Dprettier.npmPath=npm spotless:check
          ./mvnw --batch-mode jib:dockerBuild -Dmaven.test.skip -P prettierSkip

      - name: codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./target/site/jacoco/jacoco.xml

  image:
    # only build and push the image when it's a commit to master in Entur's repository
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [ tests ]
    env:
      CONTAINER_REPO: docker.io/entur/uttu
      CONTAINER_REGISTRY_USER: ${{ secrets.DOCKERHUB_LOGIN }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: set variables
        run: |
          VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "GHA_DOCKER_PUSH_IMAGE_TAG=v$VERSION-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Build container image with Jib, push to container repo
        run: |
          ./mvnw --batch-mode compile com.google.cloud.tools:jib-maven-plugin:build -Djib.to.tags=latest,${{ env.GHA_DOCKER_PUSH_IMAGE_TAG }} -Dmaven.test.skip -P prettierSkip

      - name: Tag default branch with the container image tag ${{ env.GHA_DOCKER_PUSH_IMAGE_TAG }}
        id: tag-version
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git tag --annotate "$GHA_DOCKER_PUSH_IMAGE_TAG" -m "chore(tag): $GHA_DOCKER_PUSH_IMAGE_TAG [skip ci]" --force
          git push origin "$GHA_DOCKER_PUSH_IMAGE_TAG" --force

      - name: Trigger downstream CI
        run: |
          repo_owner="entur"
          repo_name="uttu-deployment-config"
          event_type="trigger-downstream-ci"
          service="uttu"   
          echo "Triggering downstream CI for $service with version ${{ env.GHA_DOCKER_PUSH_IMAGE_TAG }}"
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITFLOW_PAT }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$GHA_DOCKER_PUSH_IMAGE_TAG\", \"unit\": false, \"integration\": true}}"